filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

- type: log
  enabled: true
  paths:
    - '/var/log/docker-lvmpy/lvmpy.log'

processors:
- add_host_metadata:
#    netinfo.enabled: false
- add_docker_metadata:
    host: "unix:///var/run/skale/docker.sock"
- decode_json_fields:
    fields: ["message", "log"]
#    target: "json"
    target: ""
    overwrite_keys: true
- script:
    lang: javascript
    source: >
      function process(event) {
          var msg = event.Get("message");
          msg = msg.replace(/\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/ig, "HIDDEN");
          msg = msg.replace(/NEK\:\w+/ig, "HIDDEN");
          event.Put("message", msg);
      }

output.logstash:
  hosts: ${FILEBEAT_HOST}

logging.json: true
logging.metrics.enabled: false
