= Denali Mainnet IMA Hotfix Soft Upgrade
include::parameters.adoc[]
:sectnums:
:sectnumlevels: 1

[WARNING]
Be sure to follow specific upgrade schedule assigned to your node(s). Follow guidance from the core team.

[NOTE]
With the 2.0.2 version, please note that the SKALE node docker now listens on an additional socket which is located in /var/run/skale/docker.sock.
A new socket path will be added to daemon.json config during update. In addition, the service configuration for docker daemon will be changed to ensure that /var/run/skale is created.

[WARNING]
If a node has custom docker daemon service configuration (systemd unit file), update may lead to unexpected behavior. In this case it's better to ask for the assistance from the core team.

[NOTE]
Please, don't forget to run `skale node check` as a last step.


== Install SKALE Node CLI

=== Download the SKALE Node CLI binary

Make sure `VERSION_NUM` is `{node-cli}`

**Terminal Command:**

```shell
VERSION_NUM=[VERSION_NUM] && sudo -E bash -c "curl -L https://github.com/skalenetwork/skale-node-cli/releases/download/$VERSION_NUM/skale-$VERSION_NUM-`uname -s`-`uname -m` >  /usr/local/bin/skale"

```

=== Make the SKALE Node CLI binary executable
**Terminal Command:**


```shell
sudo chmod +x /usr/local/bin/skale
```

== Update node using skale node update

=== Change directory

```shell
cd  ~ && vi .env
```

=== Update .env

Make sure the following options are set

[source, subs="attributes"]
----
CONTAINER_CONFIGS_STREAM={CONTAINER_CONFIGS_STREAM}
IMA_CONTRACTS_ABI_URL={IMA_CONTRACTS_ABI_URL}
DISABLE_IMA={DISABLE_IMA}
----

=== Perform update

Run skale node update:

```shell
skale node update .env
```

== Run skale node check to make sure your node is configured properly

```shell
skale node check 
```
