= {Network} Hotfix 5
include::parameters.adoc[]
:sectnums:
:sectnumlevels: 1

== Note about upcoming ETH Merge

After The Merge a Mainnet node operator must run both an execution client and a consensus client at the same time. 

[IMPORTANT]
It is a requirement to run Geth as an execution client. 

We highly recommend using Prysm as a consensus client because it's the one which SKALE software is being tested on. You can find complete installation instructions https://docs.prylabs.network/docs/install/install-with-script[here]. 


== Install SKALE Node CLI

=== Download the SKALE Node CLI binary

Make sure `VERSION_NUM` is `{node-cli}`

```shell
VERSION_NUM=[VERSION_NUM] && sudo -E bash -c "curl -L https://github.com/skalenetwork/skale-node-cli/releases/download/$VERSION_NUM/skale-$VERSION_NUM-`uname -s`-`uname -m` >  /usr/local/bin/skale"

```

=== Make the SKALE Node CLI binary executable

```shell
sudo chmod +x /usr/local/bin/skale
```

== Update node using skale node update

[IMPORTANT]
During the update procedure images without corresponding container will be removed

=== Change directory

```shell
cd  ~ && vi .env
```

=== Update .env

Make sure the following options are set

[source, subs="attributes"]
----
CONTAINER_CONFIGS_STREAM={CONTAINER_CONFIGS_STREAM}
MANAGER_CONTRACTS_ABI_URL={MANAGER_CONTRACTS_ABI_URL}
IMA_CONTRACTS_ABI_URL={IMA_CONTRACTS_ABI_URL}
----

=== Perform update

Run skale node update:

```shell
skale node update .env
```
